# Generated by Django 4.1.5 on 2023-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='style',
            new_name='name_style',
        ),
    ]
