# Generated by Django 4.1.5 on 2023-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='optimal_temperature',
            field=models.JSONField(),
        ),
    ]
