# Generated by Django 4.1.5 on 2023-07-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_clothes_optimal_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='type_of_clothes',
        ),
        migrations.AddField(
            model_name='clothes',
            name='type_of_clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_clothes', to='wardrobe.typeofclothes'),
        ),
    ]
