# Generated by Django 4.1.5 on 2023-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_remove_clothes_type_of_clothes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='style',
            field=models.ManyToManyField(blank=True, to='wardrobe.style'),
        ),
    ]
