# Generated by Django 4.1.5 on 2023-10-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        ('wardrobe', '0004_style_clothes_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.ManyToManyField(blank=True, to='weather.season'),
        ),
    ]
