# Generated by Django 4.1.5 on 2023-10-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_country_client_region_alter_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
