# Generated by Django 4.1.5 on 2023-11-21 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_clothes', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('optimal_temperature', models.JSONField(blank=True)),
                ('photo_of_clothes', models.ImageField(blank=True, null=True, upload_to='wardrobe/clothes')),
                ('favorites', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('season', models.ManyToManyField(blank=True, to='weather.season')),
                ('style', models.ManyToManyField(blank=True, to='wardrobe.style')),
                ('type_of_clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_clothes', to='wardrobe.typeofclothes')),
            ],
        ),
    ]
