# Generated by Django 4.1.5 on 2023-11-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_rename_style_clothes_name_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='brand',
            new_name='brande',
        ),
    ]
