# Generated by Django 4.1.5 on 2023-11-21 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe', '0003_rename_brand_clothes_brande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='brande',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='name_style',
            new_name='style',
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_dict', models.JSONField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
