# Generated by Django 4.1.5 on 2023-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_rename_brande_clothes_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
