# Generated by Django 4.1.5 on 2024-01-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_preset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
